### ISSUE TITLE
测试结果优化,测试结果只是展示类型的话,那和你引用的那个库也没啥区别啊.

### ISSUE THREAD

**Issue by sgf** [snltty/ntt#1]
应该直接告诉用户,能不能.
如果有限制,还要展示,对端是什么的情况下不能打洞.

**Comment by snltty** [comment]
几乎无法准确判断是否可以打洞，即使两边都不是NAT4，也可能无法打洞，除了NAT类型， 路由器也有其它的特性会导致无法打洞

**Comment by sgf** [comment]
我的意思是 使用者还得去查一下,什么是NAT4,NAT4要和什么组合才能打洞之类的.
